var rule = {
  title: '4k电影馆',
  host: 'https://4kdyg.com',
  url: '/index.php/api/vod#type=fyclass&page=fypage',
  searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
  //class_parse: '.swiper-wrapper li;a&&Text;a&&href;/(\\d+).html',
  class_name:'电影&剧集&综艺&动漫&4K精选&短剧&B站',
  class_url:'1&2&3&4&25&20&27',
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  play_parse: true,
  lazy: '',
  limit: 6,
  推荐: '.flex.wrap.border-box.public-r.hide-b-20.diy-center;.public-list-div;img&&alt;img&&data-src;.public-prt&&Text;a&&href',
  double: true,
  一级: 'js:let body=input.split("#")[1];let t=Math.round(new Date/1e3).toString();let key=md5("DS"+t+"DCC147D11943AF75");let url=input.split("#")[0];body=body+"&time="+t+"&key="+key;print(body);fetch_params.body=body;let html=post(url,fetch_params);let data=JSON.parse(html);VODS=data.list.map(function(it){it.vod_pic=urljoin2(input.split("/i")[0],it.vod_pic);return it});',
  二级: {
    title: 'h3&&Text;.slide-info-remarks:eq(2)&&Text',
    img: '.detail-pic img&&data-src',
    desc: '.slide-info.hide:eq(4)&&Text;.slide-info-remarks:eq(0)&&Text;.slide-info-remarks:eq(1)&&Text;.slide-info.hide:eq(3)&&Text;.slide-info.hide:eq(2)&&Text',
    content: '.text.cor3&&Text',
    tabs: '.anthology-tab&&a--span',
    lists: '.anthology-list-play:eq(1):eq(#id) li',
  },
  搜索: '*',
}